// language/javascript/vue/styde/1/vue-project/src/components/ui/MySelect.vue
<template >
    <select  :value="modelValue" @change="changeOption">
        <option disabled value="">Выберите из списка</option>
        <option v-for="option in options" :key="option.value" :value="option.value">{{ option.name }}</option>
    </select>
</template>
<script>
export default {
    name: 'my-select',
    props: {
        modelValue: {
            type: String
        },
        options: {
            type: Array,
            default: () => {}
        }
    },
    methods: {
        changeOption(event) {
            this.$emit('update:modelValue', event.target.value)
        }
    }
}
</script>
<style >
    
</style>

// language/javascript/react/OnYrok/src/components/Select/MySelect.jsx
import React from 'react'

function MySelect({ option, defaultValue, value, onChange}) {
    return (
        <select value={value}
        onChange={event => onChange(event.target.value)}>
            <option disabled value="value">{defaultValue}</option>
            {option.map(option =>
                <option key={option.value} value={option.value}>
                    {option.name}
                </option>
            )}
        </select>
    )
}

export default MySelect
